# Generated by Django 5.1.1 on 2024-11-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_phim_do_tuoi_binhluan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phim',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
