# Generated by Django 5.1.1 on 2024-11-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_combo_img_combo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ve',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='ve',
            name='ghe_ngoi',
        ),
        migrations.AddField(
            model_name='ve',
            name='combo',
            field=models.ManyToManyField(blank=True, to='database.combo'),
        ),
        migrations.AddField(
            model_name='ve',
            name='ghe_ngoi',
            field=models.ManyToManyField(to='database.ghengoi'),
        ),
    ]
