# Generated by Django 5.1.1 on 2024-11-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_ve_combo_remove_ve_ghe_ngoi_ve_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phim',
            name='gia_ve',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
