# Generated by Django 5.1.1 on 2024-11-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_phim_gia_ve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phim',
            name='gia_ve',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=10),
        ),
    ]
