# Generated by Django 5.1.1 on 2024-11-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_phim_gia_ve'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
