# Generated by Django 5.1.1 on 2024-11-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_nguoidung_last_login_alter_nguoidung_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ve',
            name='link_face',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
