# Generated by Django 5.1.1 on 2024-11-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_ve_link_face'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ve',
            name='gia_ve',
        ),
        migrations.RemoveField(
            model_name='ve',
            name='loai_ghe',
        ),
        migrations.AlterField(
            model_name='ve',
            name='link_face',
            field=models.ImageField(default='face/default_face.jpg', upload_to='face/'),
        ),
    ]
