# Generated by Django 5.1.1 on 2024-11-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_remove_ve_gia_ve_remove_ve_loai_ghe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ve',
            name='ma_qr_ve',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
