# Generated by Django 5.1.1 on 2024-11-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_ve_ma_qr_ve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ve',
            name='ma_qr_ve',
            field=models.CharField(default='', max_length=500),
        ),
    ]
