# Generated by Django 5.1.2 on 2024-11-12 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
