# Generated by Django 5.1.2 on 2024-11-12 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_nguoidung_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('new_user', 'Người Mới'), ('holiday', 'Ngày Lễ')], max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_value', models.FloatField()),
                ('discount_type', models.CharField(choices=[('percentage', 'Giảm Theo Phần Trăm'), ('fixed', 'Giảm Cố Định')], max_length=20)),
                ('min_amount_required', models.FloatField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('required_movies_watched', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_used', models.DateTimeField(blank=True, null=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.voucher')),
            ],
        ),
    ]
