# Generated by Django 5.1.3 on 2024-11-30 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Migration 0021
class Migration(migrations.Migration):
    dependencies = [
        ('database', '0020_player_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',  # Đảm bảo 'name' là trường bạn muốn loại bỏ
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(to=settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.CASCADE),
        ),
    ]

