# Generated by Django 5.1.3 on 2024-11-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_nguoidung_score_alter_game_time_taken_playerscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
