# Generated by Django 5.1.3 on 2024-11-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_remove_minigame_image_remove_minigame_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phim',
            name='ad_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='phim',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='movies/'),
        ),
    ]
