# Generated by Django 5.1.3 on 2024-11-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_phim_ad_description_phim_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
