# Generated by Django 5.1.3 on 2024-12-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ad_bonus_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='ad_view_available',
            field=models.BooleanField(default=True),
        ),
    ]
