# Generated by Django 5.1.3 on 2024-12-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_game_ad_bonus_used_game_ad_view_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(max_length=20)),
                ('duration', models.IntegerField(default=30)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
